/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 08 13:25:28 GMT 2022
 */

package failing;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import failing.Failing2;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Failing2_ESTest extends Failing2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Failing2 failing2_0 = new Failing2();
      try { 
        failing2_0.throwUncaughtException("omd");
      } catch(NullPointerException e) {
         //
         // Throwing NullPointerException
         //
         verifyException("failing.Failing2", e);
      }
  }
}
